export const SET_NODES_TYPES = "SET_NODES_TYPES"
export const SET_NODES = "SET_NODES"
export const SET_COLUMNS = "SET_COLUNMS"
export const SET_TABLES = "SET_TABLES"

export const FETCH_NODES_TYPES = "FETCH_NODES_TYPES"
export const FETCH_NODES = "FETCH_NODES"
export const FETCH_COLUMNS = "FETCH_COLUNMS"
export const FETCH_TABLES = "FETCH_TABLES"

export const GET_NODES_PARENT = "GET_NODES_PARENT"
export const GET_MAP_NODES = "GET_MAP_NODES"
export const GET_MAP_TABLES = "GET_MAP_TABLES"
export const GET_MAP_NODES_TYPES = "GET_MAP_NODES_TYPES"
