version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/code
    ports:
      - '8000:8000'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/code
    ports:
      - '8080:8080'      
    depends_on:
      - server
